title: Histoplasma species Assembly and Annotation
logo: /assets/img/histoplasma.png
description: This github page breaks down the Histoplasma datasets, origin of collection, sequencing information, Genome assembly and annotation pipelines used and results.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
